FROM eclipse-temurin:21-jdk

LABEL "org.opencontainers.image.authors"="moazzam21"

COPY target/loans-0.0.1-SNAPSHOT.jar loans-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar","loans-0.0.1-SNAPSHOT.jar"]